### ISSUE TITLE
Questions about design decisions

### ISSUE THREAD

**Issue by effectfully** [AndrasKovacs/system-f-omega#1]
I'm studying your development and have a few questions about design decisions behind it, could you please answer them?

1) Why did you choose not to have fully eta-expanded types/terms:

```agda
  data Sp Γ : Kind → Kind → Set where
    ε   : ∀ {A} → Sp Γ A A
    _∷_ : ∀ {A B C} → Ty Γ A → Sp Γ B C → Sp Γ (A ⇒ B) C
```

? I see that in order to define substitution you're forced to define eta-expansion at the type-level in order to turn neutrals into NFs and prove related properties. Though, eta-expansion is really concise with such spines.

2) Why did you choose to rename types at term-level variables rather than at big lambdas? I.e. why

```agda
data _∈_ : ∀ {Γ} → Ty Γ ⋆ → Con Γ → Set where
  vz   : ∀ {Γ}{Δ : Con Γ}{A}   → A ∈ (Δ ▷ₜ A)
  vsₜ_ : ∀ {Γ}{Δ : Con Γ}{A B} → A ∈ Δ → A ∈ (Δ ▷ₜ B)
  vsₖ_ : ∀ {Γ}{Δ : Con Γ}{A B} → A ∈ Δ → T.ren top A ∈ (Δ ▷ₖ B)
```

instead of something like

```agda
data _⊢_ {Θ} Γ : Type Θ -> Set where
  ...
  Λ_ : ∀ {σ α} -> shiftᶜ Γ ⊢ α -> Γ ⊢ π σ α
```

where `shiftᶜ` shifts each type variable in a context by one ([full snippet](https://gist.github.com/effectfully/8ae112e2a99393c493642fc52aafe87f)).

3) I'd really appreciate if you say what problems you had, whether there were any interesting solutions to them and whether now you'd do some things differently.

Answers to these questions can greatly improve the readme, I think.

**Comment by AndrasKovacs** [comment]
1. 

I have fully eta-expanded types and normal terms. Neutral types have kind * and neutral terms have neutral types. I enforce this when embedding neutrals into normals.

2. 

I don't know what does or doesn't work with your definition, but strong normalization [definitely works](http://www.cs.nott.ac.uk/~psztxa/publ/tlca93.pdf) and probably hereditary subst as well. A priori, the issue with your definition is that it throws away information about the ordering of type and term binders, so we have strictly less information in typing contexts. I switched to the interleaved definition of contexts in accordance with the policy that we should reflect dependencies in types as precisely as possible. I introduced this policy because I found it difficult to mentally keep track of dependencies. Nowadays I have much more experience so the fine-grained indexing might not make as much difference to me.

3. 

I don't think hereditary subst is generally worth pursuing. It's algorithmically slow, the formalization is tedious and it doesn't work with impredicativity. The only advantage is that, being first-order, it requires less metatheory than NbE or environment machines with logical predicates, but that's not relevant if your goal is to do effective formalization in your given higher-order metatheory. For the F-omega syntax, it would be better to use NbE for normalizing types. Other than that, the term syntax seems fine to me. I would keep the interleaved contexts.

**Comment by effectfully** [comment]
Thank you, your answer helps a lot.

> I have fully eta-expanded types and normal terms. Neutral types have kind * and neutral terms have neutral types. I enforce this when embedding neutrals into normals.

Ah, I see: neutral types are not fully eta-expanded, but this is forced in `ne  : Ne Γ ⋆ → Ty Γ ⋆` which makes all `Ty`s eta-expanded. That's neat. And that:

> I see that in order to define substitution you're forced to define eta-expansion at the type-level in order to turn neutrals into NFs and prove related properties. 

is needed because a function type can be substituted for a type variable, so eta-expansion at the term level is required which in turn forces eta-expansion at the type level, because that function type may contain a `∀'`, right?

**Comment by AndrasKovacs** [comment]
> is needed because a function type can be substituted for a type variable, so eta-expansion at the term level is required which in turn forces eta-expansion at the type level, because that function type may contain a ∀', right?

I would say that since types are normal and eta-long, type substitution must in any case normalize and eta-expand types. Eta-expansion of neutral terms is triggered because neutral types may become canonical after hereditary substitution. A simple example is (without beta-reduction in types though):

    (λ (x : a). x)[a ↦ (∀ (a : *). a -> a)] ≡ λ (x : ∀ (a : *). a -> a). Λ (a : *). λ (y : a). x a y

**Comment by effectfully** [comment]
> I would say that since types are normal and eta-long, type substitution must in any case normalize and eta-expand types.

But in STLC substitution doesn't cause eta-expansion and at the type level in System F-omega we have all the same things related to eta as in STLC. To put it in another way, you define `sub : ∀ {Γ A B} → (v : A ∈ Γ) → Ty (drop v) A → Ty Γ B → Ty (subᶜ v) B` before `η : ∀ {Γ A} → A ∈ Γ → Ty Γ A`.

Thank you. Feel free to close the issue.

**Comment by AndrasKovacs** [comment]
> But in STLC substitution doesn't cause eta-expansion

Yeah, I was wrong about that.
